title: BRG Trainings
title_htm: >-
  <span class="blue">B</span><span class="red">R</span><span class="green">G</span> Trainings
email: contact@brgtrainings.com
description: >-
  A Platform for Self-Learners to a Career in Software Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brgtrainings.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets # local images: ending without forward slash
# image_base_url: https://brgtrainings.sirv.com/brgtrainings.com/mainsite # cdn images: ending without forward slash
thumbnail: thumbnail.jpg

author: BRG
author_url: https://freelancerbrg.com

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: UA-164576022-1
# Disqus Comments
disqus:
  shortname: brg-trainings

contacts:
  facebook:
    url: https://www.facebook.com/cooolbrg
    label: Facebook
    class: fab fa-facebook-f
  twitter:
    url: https://twitter.com/coolbrg/
    label: Twitter
    class: fab fa-twitter
    username: "@coolbrg"
  github:
    url: https://github.com/coolbrg/
    label: GitHub
    class: fab fa-github
  linkedin:
    url: https://www.linkedin.com/in/coolbrg
    label: LinkdIn
    class: fab fa-linkedin-in
  email:
    url: mailto:budhramgurung@gmail.com
    label: Email
    class: fas fa-envelope
  youtube:
    url: https://www.youtube.com/channel/UC1mixqcP6GIY9bnG4gWDznA
    label: YouTube Channel
    class: fab fa-youtube

collections:
  tutorials:
    output: true
  getting_tastes:
    output: true
  exercises:
    output: true
  projects:
    output: true
  bootcamps:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"
permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
