title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets/img # ending without forward slash
thumbnail_path: "profile_pic.png"

twitter_username: jekyllrb
github_username:  jekyll

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: # add your google analytics id

paginate: 6
paginate_path: "/blogs/page:num"
permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
