title: BRG Trainings
email: contact@brgtrainings.com
description: >-
  Training resource materials of BRG
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brgtrainings.com" # the base hostname & protocol for your site, e.g. http://example.com
# image_base_url: /assets # local images: ending without forward slash
image_base_url: https://brgtrainings.sirv.com/brgtrainings.com/mainsite # cdn images: ending without forward slash
thumbnail_path: "profile_pic.png"

author: BRG
author_url: https://freelancerbrg.com

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: UA-164576022-1

collections:
  experiences:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"
permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
